# Generated by Django 3.0.6 on 2020-05-18 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='secret',
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
    ]
