# Generated by Django 3.0.6 on 2020-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_remove_delegate_birthday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delegate",
            name="phone",
        ),
        migrations.AddField(
            model_name="delegate",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="delegate",
            name="street",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
