# Generated by Django 3.0.4 on 2020-05-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_votation_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votation',
            options={'ordering': ['block', 'title']},
        ),
    ]
