# Generated by Django 3.0.6 on 2020-05-21 09:44

from django.db import migrations, models

import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0009_vote_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegate",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="delegate",
            name="secret",
            field=models.CharField(
                default=vote.models.generate_password, max_length=100
            ),
        ),
    ]
