# Generated by Django 3.0.6 on 2020-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0010_auto_20200521_0944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="secret",
            field=models.CharField(max_length=80),
        ),
    ]
