# Generated by Django 3.0.6 on 2020-09-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_auto_20200908_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteset',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
