# Generated by Django 3.0.6 on 2020-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0018_voteset_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="votation",
            name="display_sections",
            field=models.BooleanField(default=True),
        ),
    ]
