# Generated by Django 3.0.6 on 2020-09-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0019_votation_display_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='votation',
            name='min_choices',
            field=models.IntegerField(default=0),
        ),
    ]
