# Generated by Django 3.0.6 on 2020-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0020_votation_min_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="votation",
            name="show_absolute_majority",
            field=models.BooleanField(default=True),
        ),
    ]
