# Generated by Django 3.0.6 on 2020-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0022_votation_show_end_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='votation',
            name='counted_votation',
            field=models.BooleanField(default=False),
        ),
    ]
