# Generated by Django 3.0.6 on 2020-10-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0023_votation_counted_votation"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
