# Generated by Django 3.1.4 on 2021-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0024_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='secret',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(max_length=240),
        ),
    ]
