# Generated by Django 3.1.4 on 2021-11-26 13:13

from django.db import migrations, models
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0025_auto_20210609_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="votation",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="votation",
            name="allow_intermediate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="votation",
            name="end_date",
            field=models.DateTimeField(default=vote.models.future_date),
        ),
        migrations.AlterField(
            model_name="votation",
            name="min_choices",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="votation",
            name="show_absolute_majority",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="votation",
            name="show_end_results",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="votation",
            name="start_date",
            field=models.DateTimeField(default=vote.models.future_date),
        ),
    ]
